### ISSUE TITLE
TypeError: 'module' object is not iterable 

### ISSUE THREAD

**Issue by vaaaaanquish** [vaaaaanquish/gokart-pipeliner#5]
```
ERROR: Error in event callback for 'event.core.start'
Traceback (most recent call last):
  File "python3.6/site-packages/luigi/task.py", line 275, in trigger_event
    callback(*args, **kwargs)
  File "python3.6/site-packages/gokart/task.py", line 452, in _dump_module_versions
    self.dump(self._get_module_versions(),
  File "python3.6/site-packages/gokart/task.py", line 469, in _get_module_versions
    version = '.'.join([str(v) for v in module.__version__])
TypeError: 'module' object is not iterable
```
```
<module 'poetry.__version__' from 'python3.6/site-packages/poetry/__version__.py'>
```

**Comment by vaaaaanquish** [comment]
This is gokart's bug...:( https://stackoverflow.com/questions/7121802/module-name-in-sys-modules-and-globals
